ナビバーの実装
yanbaru-expert/team_project_52 pull request #36
Opened 2021-06-06 14:24 UTC by YOU310

close #11

## 実装内容
- ナビバーの追加
  - ロゴの追加
  - リンクを設定
  - ハンバーガーメニュー
  - レスポンシブ対応

## 参考資料
[【公式】Bootstrap（Navbar）](https://getbootstrap.jp/docs/4.5/components/navbar/)
[【やんばるエキスパート教材】メッセージ投稿アプリ（その3・Bootstrap）](https://www.yanbaru-code.com/texts/271)
[【やんばるエキスパート教材】画像ファイルが表示されない](https://www.yanbaru-code.com/questions/59)
[【Rails】「link_to」でaタグ内に画像を設置したい](https://qiita.com/hacchi56/items/c357c07481564066c2f1)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## 備考
`issue`の**実装内容**
・PHPテキスト教材のパスは texts_path(genre: "php"), 動画教材は movies_path(genre: "php") とすること
の部分が何を指しているのかが分かりませんでした
リンクは**動作確認**の表を使用して、ページ移動の確認もできています

2021-06-07 12:59 UTC, great084 requested changes
画面の表示はOKです。（ハンバーガメニューもきちんと実装できています）

リンク設定の部分に関して、ソース内にもコメントしましたが、railsで推奨されているrouteのprefixを使用するようにしましょう。

>・PHPテキスト教材のパスは texts_path(genre: "php"), 動画教材は movies_path(genre: >"php") とすることの部分が何を指しているのかが分かりませんでした
>リンクは動作確認の表を使用して、ページ移動の確認もできています

`texts_path`とはリソースのprefixを使用したリンク先の設定方法です。
参考：https://pikawaka.com/rails/link_to#Prefix%E3%81%A8%E3%81%AF%EF%BC%9F
routeファイルにリソースを記載すると自動的にルールに則ったpathが生成されます。

`texts_path(genre: "php")`とは、texts_pathの引数に`genre: 'php'`を付与する記載方法です。結果的に、このパスは、ローカル環境で起動した場合、'http://localhost:3000/texts?genre=php'というURLに変換されます。

2021-06-07 12:59 UTC, great084 commented on app/views/layouts/_header.html.erb
> +  <%= link_to image_tag("yanbaru_expert_logo.png", class: "navbar-brand"), "http://localhost:3000" %>
railsでは（他のフレームワークでも）アプリ内部のリンク先のURL(ex `http://localhost:3000`)を直接書くことは、推奨されません。
`rake routes`コマンドで表示されるprefixを利用しましょう。

特にホスト名（ここで言うlocalhost)を直書きすると、 heorkuへアップする際にアクセスできなくなってしまうためNGです。アプリ内リンクではurlではなく、pathを記載するようにしましょう。

※参考：https://pikawaka.com/rails/link_to#Prefixとは？

同様の箇所が何点かあるので修正お願いします。

2021-06-07 13:57 UTC, YOU310 commented on app/views/layouts/_header.html.erb
> +  <%= link_to image_tag("yanbaru_expert_logo.png", class: "navbar-brand"), root_path %>
修正箇所

2021-06-07 13:57 UTC, YOU310 commented on app/views/layouts/_header.html.erb
> +          <%= link_to "Ruby/Rails動画教材", movies_path, class: "dropdown-item" %>
修正箇所

2021-06-07 13:57 UTC, YOU310 commented on app/views/layouts/_header.html.erb
> +          <%= link_to "PHP動画教材", movies_path(genre: "php"), class: "dropdown-item" %>
修正箇所

2021-06-08 00:40 UTC, great084 approved these changes
OKです。

2021-06-08 01:16 UTC, merged