ゲストログイン機能の実装
yanbaru-expert/team_project_52 pull request #40
Opened 2021-06-09 00:31 UTC by clock2222

close #20

## 実装内容

- ゲストログイン機能の実装
 - ナビバーにゲストログインのリンクを追加
 - メールアドレスは`test@example.com`に指定

## 参考資料（必要があれば）

[【やんばるエキスパート教材】ゲストログイン機能の実装](https://www.yanbaru-code.com/texts/392)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## 備考（必要があれば）
`rubocop -a`実行
`app/controllers/users/sessions_controller.rb:1`にて、ネストしたクラス名が違反。
>Class Users::SessionsController < Devise::SessionsController

`.rubocop.yml`に違反を許可する設定にすると反対にネストのないクラスが違反者になる様子。
```
ClassAndModuleChildren:
  EnforcedStyle: compact
```

今回は`git commit -n`で違反をパスしましたが、今後`rubocop -a`を走らせるたびにプロジェクト全員が違反を警告される可能性があると思いました。

>Class Users::SessionsController < Devise::SessionsController
ネストを解消してみようと試みましたが、継承元のネストの扱いがわかりませんでした。

今回の場合はどのように対処するべきでしょか。

2021-06-09 13:33 UTC, YOU310 commented
LGTM!

2021-06-09 13:56 UTC, great084 requested changes
@clock2222 
Issueの要件としてあげられている、「ログイン・新規登録のページにゲストログインボタン」がありません。

2021-06-09 13:57 UTC, YOU310 commented
備考の件ですが、app/controllers/users/session_controller.rbにて記述を
```
class Devise
  class Users
    def guest_sign_in
      sign_in User.guest
      redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
    end
  end
end
```
にすると無理矢理解決できそうですが、果たして必要なのかは分からないです。。。

2021-06-09 14:22 UTC, great084 commented
備考の件ですが、

rubocopが言っている通り、compaceスタイルではなく、nestedスタイルに変更しましょう。

↓こんな感じになると思います。

```
Module Users
  class SessionsController < Devise::SessionsController
~
  end
end
```

ちなみに、rubocopに出力されたメッセージには、`1 offense detected, 1 more offense can be corrected with 'rubocop -A'と出るはずです。
普段は使うのはあまりおすすめできませんが、今回は`rubocop -A` (大文字のA)を実施して、コードの修正内容確認＆きちんと当該クラス・メソッドが呼び出されているか確認しましょう。

2021-06-09 23:34 UTC, clock2222 commented
ありがとうございます。
大変参考になりました。`rubocop -A`は非推奨という認識だったので選択肢に入れていませんでした。品質が保証されていないだけでチェックを行えば問題ないという認識で改めたいと思います。
下部のゲストログインボタンは見落としていました。失礼しました。
`rubocop -A`にてコードの修正。コンソールにて、修正箇所の呼び出し確認。
````
[6] pry(main)> user = Users::SessionsController.new
=> #<Users::SessionsController:0x0000000000bf40>
[7] pry(main)> user.class
=> Users::SessionsController
[8] pry(main)> user.class.superclass
=> Devise::SessionsController
```
動作確認も問題ありませんでした。
確認よろしくお願いします。

2021-06-10 00:38 UTC, great084 approved these changes
LGTM

2021-06-10 01:34 UTC, merged