rails 動画教材ページの実装
yanbaru-expert/team_project_52 pull request #41
Opened 2021-06-09 10:21 UTC by YOU310

close #16

## 実装内容
- `Cards`,`Grid System`を利用してRails動画教材の一覧を表示

## 参考資料（必要があれば）
[【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
[【公式】Bootstrap Grid System](https://getbootstrap.jp/docs/4.5/layout/grid/)
[【やんばる教材】Youtube動画の投稿](https://www.yanbaru-code.com/texts/349)
[動画の埋め込み（Embeds）](https://v4.bootstrap-guide.com/utilities/embed)
[Railsのpartialでcollectionを渡すときにはindexの変数が自動的に作られる](https://qiita.com/otakumesi/items/74a75cd6ebff7eba5c63)
[とほほのBootstrap 4入門 -Grid-](https://www.tohoho-web.com/bootstrap/grid.html)
[Bootstrapのグリッドを理解する【図解たっぷりBootstrap入門】](https://skillhub.jp/courses/168/lessons/915)
[【Rails】条件に応じてデータを取得する](https://qiita.com/Hal_mai/items/babb19560ace072c99f5)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## 備考
- `rubocop -a`の際、`Freeze mutable objects assigned to constants`が表示されるのですが、`RAILS_GENRE_LIST = %w[basic git ruby rails]`に.`freeze`を付けると解決されます
 ` .freeze`してしまった方がいいのでしょうか？
- 装飾に関してですが`.scss`に書き込むべきなのか、`class`内に書き込むべきなのかの区別がイマイチ分かっていません
  もしおかしな記述があれば指摘いただけると嬉しいです

2021-06-09 14:57 UTC, great084 requested changes
>rubocop -aの際、Freeze mutable objects assigned to constantsが表示されるのですが、RAILS_GENRE_LIST = %w[basic git ruby rails]に.freezeを付けると解決されます
>.freezeしてしまった方がいいのでしょうか？

freezeしましょう。（定数は上書きできないようにしておくため）

>装飾に関してですが.scssに書き込むべきなのか、class内に書き込むべきなのかの区別がイマイチ分かっていません
もしおかしな記述があれば指摘いただけると嬉しいです

bootstrapで定義済みクラスのオーバライドについてコメントしました。
本来スタイルはcss(scss)で定義すべきものですが、今回はbootstrapを利用しているので、bootstrapのスタイルクラスを利用してもOKです。（ex. margin,padding,text-alignなど）

2021-06-09 14:57 UTC, great084 commented on app/assets/stylesheets/movies.scss
> +}
基本的にbootstrapで定義されているclassをオーバライドするのは、やめましょう。
この場合、他のbootstrapのbtnクラスを利用している箇所（ex. ログイン画面）の設定も変更されてしまいます。
※オーバライドしてよいのは、プロジェクト全体でboostrapの該当クラスの設定を変更する場合です。

特定箇所のレイアウトを変更したい場合には、個別にクラスを設定しそのクラスにスタイルを当てましょう。

2021-06-10 06:11 UTC, YOU310 commented on app/assets/stylesheets/movies.scss
> +}
ありがとうございます
他に影響し得る箇所は、独自の`class`を設定して専用スタイルを当てていく感じですね！
`movies.scss`内の記述は`movies_controller`に適用されると勘違いしていましたが、視覚的に区別するためにファイルを分けているって認識で大丈夫でしょうか？

2021-06-10 06:16 UTC, YOU310 commented on app/models/movie.rb
> +  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze
.freeze化

2021-06-10 06:16 UTC, YOU310 commented on app/views/movies/_movie.html.erb
> +<div class="card-base col-sm-6 col-md-4">
`class`名修正

2021-06-10 06:16 UTC, YOU310 commented on app/views/movies/_movie.html.erb
> +      <a href="#" class="btn btn-dokuha btn-secondary">読破済みにする</a>
`class`名修正

2021-06-10 06:16 UTC, YOU310 commented on app/views/movies/_movie.html.erb
> +      <p class="card-title rails-card-title">Lv.<%= "#{movie_counter +1}" %>：<%= movie.title %></p>
`class`名修正

2021-06-10 06:16 UTC, YOU310 commented on app/views/movies/index.html.erb
> +<h1 class="rails-movies-title">Ruby/Rails 動画</h1>
`class`名修正

2021-06-10 12:33 UTC, great084 commented on app/assets/stylesheets/movies.scss
> +}
>movies.scss内の記述はmovies_controllerに適用されると勘違いしていましたが、視覚的に区別するためにファイルを分けているって認識で大丈夫でしょうか？

その理解であっています。
あくまで開発時の視認性を考えて分割していますが、最終的にブラウザに呼び出されるCSSは一本にまとまっています。

2021-06-10 12:33 UTC, great084 approved these changes

2021-06-10 12:46 UTC, YOU310 commented on app/assets/stylesheets/movies.scss
> +}
ありがとうございます！

2021-06-10 12:47 UTC, merged