テキスト教材の読破済み機能　＃２３
yanbaru-expert/team_project_52 pull request #44
Opened 2021-06-13 11:43 UTC by ryotagit

close #23

## 実装内容

- 視聴済み機能に使用する WatchProgress モデルを作成
  - 外部キー設定を行い，ユニーク制約を入れてからマイグレーション
  - バリデーションをモデルに追加
  - 関連付けを入れる（User と Movie の関連付けは使用しないので入れていない）
- 動画教材一覧ページに視聴済み機能を実装
  - 非同期で処理できるようにすること(app/views/read_progresses の中の２つのファイルに記述)
- `read_progresses_controller.rb`に `redirect_to root_path`を追加
  - ページをボタンを押すたびにページをリロードしないと見た目に反映されなかったため
  

## 参考資料（必要があれば）
- render の理解
  - https://qiita.com/iverson3kobe0824/items/25f6e057caf6f96d617f
  - https://qiita.com/Izushi/items/caeec7cf00d0bb82d728
- Link_toをボタンにする
  - https://qiita.com/maru_katy/items/5d352951161ebd9b2e3a
- [【やんばるエキスパート教材】モデルの関連付け その2（多対多)](https://www.yanbaru-code.com/texts/297)
- 変数の受け渡し
  - https://qiita.com/ozipi/items/6df659a34f12b6b753ce 

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-06-13 14:55 UTC, YOU310 commented on app/views/read_progresses/create.js.erb
> +document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read_progress", post: @text) %>'
ボタンを押すたびにリロードしないと反映されないのは、ここの記述に間違いがあるからです
ただここを修正すると別の問題が発生してしまうので、今度はそちらも要修正です

2021-06-13 14:55 UTC, YOU310 commented on app/views/read_progresses/destroy.js.erb
> +document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/disread_progress", post: @text) %>'
同様にこちらにも記述の間違いがあります

2021-06-13 15:03 UTC, YOU310 commented on s.delete_all
> +  updated_at: [1;34;4mSat[0m, [1;34m12[0m [1;34;4mJun[0m [1;34m2021[0m [1;34m16[0m:[1;34m37[0m:[1;35m58.813327000[0m [1;34;4mJST[0m [1;34m+09[0m:[1;34m00[0m[32m>[0m]
このファイルがちょっとよく分からないのですが、何をする為のものですか？

2021-06-13 15:07 UTC, YOU310 commented on app/models/text.rb
> +  end
微妙にN+1問題が解決できていない気がします

2021-06-14 08:05 UTC, great084 requested changes
動作的にはうまく行っているようにも見えますが、要件である非同期通信（＆部分テンプレート反映）が実装されていなので、コメント確認の上、修正お願いします。

2021-06-14 08:05 UTC, great084 commented on app/controllers/read_progresses_controller.rb
> +    redirect_to root_path
redirectしてしまうと、非同期通信による部分レンダリングが実装できません。(別途作成した`app/views/read_progresses/create.js.erb`がレンダーされるようにしましょう）

2021-06-14 08:05 UTC, great084 commented on app/views/read_progresses/create.js.erb
> +document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read_progress", post: @text) %>'
renderの引数が適切かどうか確認しましょう。render先のファイルでどんな変数名で何を受け取っているか確認できると良いと思います。

2021-06-14 08:05 UTC, great084 commented on app/views/texts/_text.html.erb
> +  <div class="card mx-auto" id="text-<%= text.id %>">
card全体に、`create.js.erb`などの`documet.getElementById`で、指定されるidを指定すると、画像なども含めてcard全体が置き換わってしまいます。
置き換えたい対象（今回の場合は「読破済み」ボタンだけなはず）に対して、指定するようにしましょう。

2021-06-14 08:05 UTC, great084 commented on s.delete_all
> +  updated_at: [1;34;4mSat[0m, [1;34m12[0m [1;34;4mJun[0m [1;34m2021[0m [1;34m16[0m:[1;34m37[0m:[1;35m58.813327000[0m [1;34;4mJST[0m [1;34m+09[0m:[1;34m00[0m[32m>[0m]
不要であれば削除してください。

2021-06-21 12:13 UTC, great084 approved these changes
動作、コードともほぼOKです。
一点、ymlファイルのレイアウトだけ修正お願いします！
（軽微な修正ですので、追加レビュー不要でマージしてOKです）

2021-06-21 12:13 UTC, great084 commented on config/locales/ja.yml
> +      　text: テキスト教材
ymlファイルはインデントが命です。
字下げがずれていると、うまく変換できないと思います。

2021-06-22 14:59 UTC, great084 commented on config/locales/ja.yml
> +    　read_progress:
rails console実行すると以下のエラーが出力されました。
多分このあたりに全角スペース？かなにか入っていると思います。

```
Users/hiro/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/i18n-1.8.10/lib/i18n/backend/base.rb:245:in `rescue in load_yml': can not load translations from /Users/hiro/app/team_project/config/locales/ja.yml: #<Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 3 column 5> (I18n::InvalidLocaleData)
以下略
```

空白部が半角スペース以外のものが入っていないか確認しすると、rails consoleなどでエラーが出力されないことを確認してください。

2021-06-22 23:37 UTC, ryotagit commented on config/locales/ja.yml
> +    　read_progress:
一つだけ全角スペースが入り込んでいましたので修正しました

2021-06-23 13:48 UTC, great084 approved these changes
お疲れさまでした！LGTMです!

2021-06-24 00:01 UTC, merged